# Auto-generated pytest script for: tc_fap_04_5005
# Generated by TestScriptGeneratorLibrary  2026-05-12 03:08:18
# DO NOT EDIT MANUALLY — re-generate from the source .txt script.

import time

def test_tc_fap_04_5005(cyfastobj, request):
	cyfastobj.cam_layout_1()
	cyfastobj.tc_fap_global_1()
	# PDL: drive HSI to required state
	cyfastobj.set_page('0x00')
	cyfastobj.set_state('0x01','0x03')
	cyfastobj.end_page()
	cyfastobj.set_page('0x01')
	cyfastobj.set_state('0x03000104','0x0b')
	cyfastobj.end_page()
	cyfastobj.set_page('0x01')
	cyfastobj.set_state('0x03000104','0x0b')
	cyfastobj.end_page()
	cyfastobj.set_page('0x04')
	cyfastobj.set_state('0x03000481','11')
	cyfastobj.set_state('0x03000483','11')
	cyfastobj.set_state('0x03010483','11')
	cyfastobj.set_state('0x03020483','11')
	cyfastobj.set_state('0x03130483','11')
	cyfastobj.set_state('0x03140483','11')
	cyfastobj.set_state('0x03000417','3')
	cyfastobj.set_state('0x03010417','1')
	cyfastobj.set_state('0x03020417','1')
	cyfastobj.set_state('0x03030417','3')
	cyfastobj.set_state('0x03040417','3')
	cyfastobj.set_state('0x03050417','1')
	cyfastobj.set_state('0x03060417','1')
	cyfastobj.set_state('0x03070417','3')
	cyfastobj.set_state('0x03080417','1')
	cyfastobj.set_state('0x03090417','3')
	cyfastobj.set_state('0x030a0417','3')
	cyfastobj.set_state('0x030b0417','3')
	cyfastobj.set_extended_state('0x00000447','0')
	cyfastobj.end_page()
	#To be Done -> UM "Please open the fly-out menu and select Cabin Lighting Control Page button"
	cyfastobj.find_element_and_click_visual("/mnt/user-data/outputs/ref/CIL_/select.png", request)
	cyfastobj.find_element_and_click_visual("/mnt/user-data/outputs/ref/CIL_/Cabin.png", request)
	#To be Done -> UP "Verify that a Select Button is visible in the Global Section Entire Scenario Panel.Proceed to continue"
	ret_val = cyfastobj.find_element_if_present_visual("/mnt/user-data/outputs/ref/CIL_/Select_Button.png", request) #ToBeChecked
	if ret_val is not None:
		x, y = ret_val
		assert x > 125 and y > 374, "Select Button is not present"
	else:
		assert False, "Select_Button.png is not found"
	#To be Done -> UP "Verify that on clicking select on Entire Scenario Panel  a panel opens having twelve different scenarios.\nProceed to continue"
	expected_text_roi = [0, 336, 121, 381]
	assert cyfastobj.get_screenshot_and_verify_text("clicking", expected_text_roi, request), "clicking select on Entire Scenario Panel text not present"
	#To be Done -> UP "Verify that Breakfast scenario is indicated as Run."
	#assert cyfastobj.get_screenshot_and_verify_text("Run",[504,370,563,415],request), "Breakfast scenario Running text is not present"
	ret_val = cyfastobj.find_element_if_present_visual("/mnt/user-data/outputs/ref/CIL_/Breakfast_scenario.png", request) #ToBeChecked
	if ret_val is not None:
		x, y = ret_val
		#assert x > 504 and y > 370, "Breakfast scenario not in expected state"
	else:
		assert False, "Breakfast_scenario.png is not found"
	#To be Done -> UP "Click on cancel.verify that scenario panel is invisible/removed."
	cyfastobj.find_element_and_click_visual("/mnt/user-data/outputs/ref/CIL_/cancel.png", request)
	ret_val = cyfastobj.find_element_if_present_visual("/mnt/user-data/outputs/ref/CIL_/scenario_panel_is.png", request) #ToBeChecked
	if ret_val is None:
		#assert x > 0 and y > 336, "scenario panel is is not present"
	else:
		assert False, "scenario_panel_is.png is not found"
	#To be Done -> UP "Proceed to finish the Script."
	#To be Done -> UP "Script tc_fap_04_5005.tst finished"